---
###############################################################################
# Filename: tasks/configure.yml
# Role: ansible-role-vault
# Summary: Deploy Vault server configuration (vault.hcl and vault.env)
# Classification: UNCLASSIFIED
###############################################################################

- name: Deploy Vault server configuration
  ansible.builtin.template:
    src: vault.hcl.j2
    dest: "{{ vault_config_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ vault_config_file_mode }}"
  notify: Restart vault

- name: Deploy Vault environment file
  ansible.builtin.template:
    src: vault.env.j2
    dest: "{{ vault_env_file }}"
    owner: "{{ vault_user }}"
    group: "{{ vault_group }}"
    mode: "{{ vault_env_file_mode }}"
  notify: Restart vault
